[global/wm]
include-file = modules.ini

[bar/pam6]
monitor =
fixed-center = true

width = 21.22%
height = 40
offset-x = 9.5800000000000001%
offset-y = 0.5%

background = #BF22152B
foreground = #FDFDFD
radius = 10

; Text
font-0 = "Iosevka Nerd Font:style=Italic:pixelsize=12;2"
; Emoji
font-1 = "Font Awesome 6 Free Solid:size=9;3"
font-2 = "Material Design Icons Desktop:size=14;4"
font-3 = "Noto Color Emoji:size=10;2"

modules-center = teleprompter
